add functionality to gpgit

diff --git a/gpgit_setup b/gpgit_setup
--- a/gpgit_setup
+++ b/gpgit_setup
@@ -20,10 +20,30 @@ if ! gpg --list-secret-keys --keyid-format=long | grep -q "sec"
 then
   echo "No GPG key found. Generating a new key..."
   gpg --full-generate-key
+else 
+    echo "If you want to use an existing key, please enter 1. If you want to create a new key, please enter 2.and if want to delete a key from computer enter 3"
+    read -r input
+    if [ "$input" -eq 1 ]; then
+        echo "Using an existing key..."
+    elif [ "$input" -eq 2 ]; then
+        echo "Generating a new key..."
+        gpg --full-generate-key
+    elif [ "$input" -eq 3 ]; then
+        read -r key_ID
+        echo "Enter the key ID of the key to be deleted"
+        gpg --delete-secret-key "$key_ID"
+        gpg --delete-key "$key_ID"
+        exit 0
+    else
+        echo "Invalid input. Exiting..."
+        exit 1
+    fi
 fi
 
 GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format=long | awk '$1 ~ /sec/ { print $2 }' | cut -d'/' -f2)
 git config --global user.signingkey "$GPG_KEY_ID"
 git config --global commit.gpgsign true
-
+gpg --armor --export "$GPG_KEY_ID" > public_key.asc
+cat public_key.asc
+echo "Copy this public key and paste it into a new GPG key in your GitHub account."
 echo "GPG key setup complete."
